### ISSUE TITLE
Spigot version out of date

### ISSUE THREAD

**Issue by ErythroCraft** [Dart2112/AsyncWorldEditBossBar#2]
Hello.

You are very late to update this plugin.
Are you still working on this simple plugin?

Are you not working on this plugin or you don`t wont give upgrades, say it.

I wait 24h for an request of you.
Than we start an custom build of your work, becorse we think that you no longer online.

**Comment by Dart2112** [comment]
What is there to update?

**Comment by ErythroCraft** [comment]
spigot 1.17.2 | 1.18.2 and 1.19 (latest)

**Comment by Dart2112** [comment]
> spigot 1.17.2 | 1.18.2 and 1.19 (latest)

That doesn't matter, the plugin will still work fine until the AWE API changes enough to break it.

The APIs that this plugin interacts with in Spigot haven't changed in years and probably won't change for years

The only updates to this plugin will be when it breaks or new features are added. There is no need to push updates for minor spigot updates

**Comment by ErythroCraft** [comment]
https://builds.enginehub.org/job/worldedit/20577

**Comment by Dart2112** [comment]
> https://builds.enginehub.org/job/worldedit/20577

That's world edit, this plugin is for AWE which hasn't gotten a 1.19 update yet anyways

**Comment by Dart2112** [comment]
Personally confirmed working with latest AWE

Closing issue as it is invalid

**Comment by ErythroCraft** [comment]
Sorry. I testet for 1.17 - 1.18 - 1.19
It is working.

Maybe you can update your overview in line tested versions.

from: 
Tested Minecraft Versions: 1.16

to:
Tested Minecraft Versions: 1.16 - 1.17 - 1.18 - 1.19
